[tool.poetry]
name = "event-app"
version = "0.1.0"
description = ""
authors = ["Pavel Skobelev <pskobelev@me.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.115.5"
uvicorn = "^0.32.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
