"""userevent add user_choice

Revision ID: ad25b41b44b1
Revises: 05b154910ad9
Create Date: 2024-12-26 12:24:31.182142

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ad25b41b44b1"
down_revision: Union[str, None] = "05b154910ad9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "userevents", sa.Column("user_choice", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("userevents", "user_choice")
    # ### end Alembic commands ###
